### ISSUE TITLE
pyBibX uses older pillow version for word cloud generation

### ISSUE THREAD

**Issue by wahlau** [Valdecy/pyBibX#13]
when I run the word_cloud_plot() function, I receive this error

AttributeError: 'ImageDraw' object has no attribute 'textsize'

and I can solve it when I downgrade my pillow from 11 to 9.5.0.

**Comment by Valdecy** [comment]
This problem comes from WordCloud’s internal use of the ImageDraw.textsize method. When plt.imshow(wordcloud) is called to display the word cloud, it activates the rendering process, which relies on Pillow’s text-measuring functionality. However, beginning with Pillow 10, textsize was replaced by textbbox, and if the WordCloud package hasn't been updated to reflect this change, an error occurs during text size calculation for word placement.

To resolve this issue without downgrading Pillow, consider updating to the latest version of WordCloud. The most recent version may include patches that replace textsize with textbbox or other compatible methods.
