### ISSUE TITLE
WOS Institutions and Countries not well parsed?

### ISSUE THREAD

**Issue by ddmartinez** [Valdecy/pyBibX#2]
Data source is correct: several countries and several institutions.

But Data_table seems to have parse issues. I observe that country must be gathered from Publisher Address since there is no specific field for that. Verified that via Excel export.

I downloaded all the data according to pyBibX Introduction (all  fields checked).

This don't happen with SCOPUS (also checked).

![imagen](https://github.com/Valdecy/pyBibX/assets/34606155/2d432478-5bb3-4af5-b912-b9ec4ef15b90)

![imagen](https://github.com/Valdecy/pyBibX/assets/34606155/eb2d7269-ca42-4006-85d1-ae8455f13b22)

**Comment by Valdecy** [comment]
Hello! In order to better understand and reproduce the error you're experiencing, could you kindly share the .bib file with me?

**Comment by ddmartinez** [comment]
Olá! Of course, is a big one, a merge of four parts (+- 4000 entries). Here is the first of them (for fast check). If you need the whole file, I pickled it to a file.

[savedrecs_0.zip](https://github.com/Valdecy/pyBibX/files/12158713/savedrecs_0.zip)

Thanks in advance!

**Comment by ddmartinez** [comment]
Much better! But still, it seems that some parse issues remains: several UNKNOW_Countries and a lot of UNKNOW_Institutions. As shown in Sankey Diagram (topn=10).

![imagen](https://github.com/Valdecy/pyBibX/assets/34606155/1aa8d15f-fa67-4f12-9d88-14a82acd4842)

On the other hand, I'm using your https://arxiv.org/abs/2304.14516 as authoritative paper.

**Comment by Valdecy** [comment]
Hi there! "I have implemented some refinements in the new pyBibix 3.1.9 update, although the improvements might be marginal due to the inherent challenges with the dataset. Specifically, the dataset's lack of comprehensive and well-structured information limits the extent to which performance can be enhanced. Despite these constraints, I have tried to extract maximum performance from the given data. I would recommend you give the new version a try. Please understand that the improvement may not be substantial due to the aforementioned reasons. Your understanding and continued use of pyBibix are highly appreciated as we continue to work towards refining the product further."
